name: Update Downloads

on:
  schedule:
    - cron: "0 0 * * *" # Every UTC midnight 
  workflow_dispatch:

jobs:
  update-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install firebase-admin node-fetch node-abort-controller

      - name: Run update script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: node backend/updateDownloads.mjs
