name: Update Site Data

on:
  schedule:
    - cron: "0 0 * * *" # Every UTC midnight
  workflow_dispatch:     # Allow manual trigger
  push:
    paths:
      - '.github/workflows/update-site-data.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  # Cancel old runs to prevent queueing

jobs:
  update-contributors:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Prevent indefinite hanging
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Create assets directories
        run: mkdir -p assets/data
          
      - name: Initialize JSON file if needed
        run: |
          if [ ! -f assets/data/contributors.json ]; then
            echo '{"generated":"'"$(date -u +"%Y-%m-%dT%H:%M:%SZ")"'","source":"initial","contributors":[]}' > assets/data/contributors.json
          fi
          
      - name: Trigger initial stats calculation
        run: |
          echo "Triggering initial stats calculation..."
          curl -s https://api.github.com/repos/EuphoriaPatches/propertiesFiles/stats/contributors || true
          
      - name: Attempt to fetch Stats API data
        id: stats-api
        timeout-minutes: 5  # Limit time spent on this step
        run: |
          # Set up retry mechanism with exponential backoff
          STATS_API_SUCCESS=false
          
          # Try multiple times with increasing delays but limit total time
          for attempt in {1..5}; do  # Reduced attempts to prevent timeouts
            echo "Stats API attempt $attempt of 5..."
            
            # Reduced exponential backoff: 15s, 30s, 60s max
            sleep_time=$((15 * (2 ** (attempt - 1))))
            if [ $sleep_time -gt 60 ]; then
              sleep_time=60
            fi
            echo "Waiting $sleep_time seconds..."
            sleep $sleep_time
            
            # Try the Stats API with more verbose output
            echo "Fetching from Stats API..."
            STATUS_CODE=$(curl -s -o stats_response.json -w "%{http_code}" https://api.github.com/repos/EuphoriaPatches/propertiesFiles/stats/contributors)
            
            echo "API response status code: $STATUS_CODE"
            
            # Check if file is empty
            if [ ! -s stats_response.json ]; then
              echo "Warning: stats_response.json is empty!"
              continue
            fi
            
            # Try to validate JSON
            if [ "$STATUS_CODE" = "200" ]; then
              node -e "
                try {
                  const fs = require('fs');
                  const data = JSON.parse(fs.readFileSync('stats_response.json', 'utf8'));
                  if (Array.isArray(data) && data.length > 0) {
                    console.log('Valid array data with ' + data.length + ' items');
                    process.exit(0);
                  } else {
                    console.log('Not a valid array or empty array');
                    process.exit(1);
                  }
                } catch(e) {
                  console.error('Error parsing JSON:', e.message);
                  process.exit(1);
                }
              "
              
              if [ $? -eq 0 ]; then
                STATS_API_SUCCESS=true
                echo "Stats API returned valid data on attempt $attempt!"
                break
              fi
            fi
          done
          
          # Set output variable to indicate success or failure
          echo "success=$STATS_API_SUCCESS" >> $GITHUB_OUTPUT
          
      - name: Process Stats API data
        if: steps.stats-api.outputs.success == 'true'
        id: stats-process
        run: |
          echo "Processing Stats API data..."
          node -e '
            try {
              const fs = require("fs");
              
              // Read the existing file if it exists
              let hasChanges = true;
              let existingData = { contributors: [] };
              if (fs.existsSync("assets/data/contributors.json")) {
                existingData = JSON.parse(fs.readFileSync("assets/data/contributors.json", "utf8"));
              }
              
              const data = JSON.parse(fs.readFileSync("stats_response.json", "utf8"));
              
              // Filter out actions-user
              const filteredData = data.filter(
                contributor => contributor.author && contributor.author.login !== "actions-user"
              );
              
              // Sort by commit count
              filteredData.sort((a, b) => {
                return b.total - a.total;
              });
              
              // Simplify the data structure
              const processedData = filteredData.map(contributor => ({
                login: contributor.author.login,
                additions: contributor.weeks.reduce((sum, week) => sum + week.a, 0),
                deletions: contributor.weeks.reduce((sum, week) => sum + week.d, 0),
                commits: contributor.total,
                avatar_url: contributor.author.avatar_url,
                html_url: contributor.author.html_url
              }));
              
              // Compare with existing data (ignoring timestamp)
              if (existingData.source === "stats_api" && 
                  JSON.stringify(existingData.contributors) === JSON.stringify(processedData)) {
                console.log("No changes to contributor data detected");
                hasChanges = false;
              } else {
                console.log("Changes detected in contributor data");
                // Add timestamp
                const result = {
                  generated: new Date().toISOString(),
                  source: "stats_api",
                  contributors: processedData
                };
                
                fs.writeFileSync("assets/data/contributors.json", JSON.stringify(result, null, 2));
                console.log("Successfully created contributors.json from Stats API");
              }
              
              // Set the output for the GitHub Action
              fs.writeFileSync(process.env.GITHUB_OUTPUT, `has_changes=${hasChanges}`);
            } catch (error) {
              console.error("Error processing Stats API data:", error);
              // Do not fail the workflow, just keep the existing file
              fs.writeFileSync(process.env.GITHUB_OUTPUT, "has_changes=false");
              process.exit(0);
            }
          '
          
      - name: Fetch Simple API data
        if: steps.stats-api.outputs.success != 'true'
        id: simple-api
        timeout-minutes: 2  # Short timeout for simple API
        run: |
          echo "Stats API failed. Using Simple API as fallback..."
          curl -s https://api.github.com/repos/EuphoriaPatches/propertiesFiles/contributors > simple_response.json
          
          # Check if Simple API returned valid data
          SIMPLE_API_SUCCESS=false
          if [ "$(cat simple_response.json | node -e "try { const data = JSON.parse(process.stdin.read()); console.log(Array.isArray(data) && data.length > 0 ? 'true' : 'false'); } catch(e) { console.log('false'); }")" = "true" ]; then
            echo "Simple API returned valid data"
            SIMPLE_API_SUCCESS=true
          else
            echo "Simple API failed to return valid data"
          fi
          
          # Set output variable
          echo "success=$SIMPLE_API_SUCCESS" >> $GITHUB_OUTPUT
      
      - name: Process Simple API data
        if: steps.stats-api.outputs.success != 'true' && steps.simple-api.outputs.success == 'true'
        id: simple-process
        run: |
          node -e '
            try {
              const fs = require("fs");
              
              // Read the existing file if it exists
              let hasChanges = true;
              let existingData = { contributors: [] };
              if (fs.existsSync("assets/data/contributors.json")) {
                existingData = JSON.parse(fs.readFileSync("assets/data/contributors.json", "utf8"));
              }
              
              const data = JSON.parse(fs.readFileSync("simple_response.json", "utf8"));
              
              // Filter out actions-user
              const filteredData = data.filter(contributor => contributor.login !== "actions-user");
              
              // Sort by contributions
              filteredData.sort((a, b) => b.contributions - a.contributions);
              
              // Simplify the data structure
              const processedData = filteredData.map(contributor => ({
                login: contributor.login,
                contributions: contributor.contributions,
                avatar_url: contributor.avatar_url,
                html_url: contributor.html_url
              }));
              
              // Compare with existing data (ignoring timestamp)
              if (existingData.source === "simple_api" && 
                  JSON.stringify(existingData.contributors) === JSON.stringify(processedData)) {
                console.log("No changes to contributor data detected");
                hasChanges = false;
              } else {
                console.log("Changes detected in contributor data");
                // Add timestamp
                const result = {
                  generated: new Date().toISOString(),
                  source: "simple_api",
                  contributors: processedData
                };
                
                fs.writeFileSync("assets/data/contributors.json", JSON.stringify(result, null, 2));
                console.log("Successfully created contributors.json from Simple API");
              }
              
              // Set the output for the GitHub Action
              fs.writeFileSync(process.env.GITHUB_OUTPUT, `has_changes=${hasChanges}`);
            } catch (error) {
              console.error("Error processing Simple API data:", error);
              // Do not fail the workflow, just keep the existing file
              fs.writeFileSync(process.env.GITHUB_OUTPUT, "has_changes=false");
              process.exit(0);
            }
          '
      
      - name: Fallback notification
        if: steps.stats-api.outputs.success != 'true' && steps.simple-api.outputs.success != 'true'
        run: echo "Both APIs failed. Keeping existing contributors file."
          
      - name: Cleanup temporary files
        run: rm -f stats_response.json simple_response.json
      
      # Check if there were changes to the contributors file
      - name: Check for contributor changes
        id: check-changes
        run: |
          if [ "$(git status --porcelain assets/data/contributors.json | wc -l)" -gt "0" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          echo "Contributors changes: $(git status --porcelain assets/data/contributors.json | wc -l)"

      # Upload contributors.json as an artifact if changed
      - name: Upload contributors data artifact
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: contributors-data
          path: assets/data/contributors.json
          retention-days: 1

  update-downloads:
    runs-on: ubuntu-latest
    # Continue even if contributors job fails
    needs: update-contributors
    continue-on-error: true
    timeout-minutes: 10
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch node-abort-controller

      - name: Run download update script
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: node --trace-exit backend/updateDownloads.mjs
        
      - name: Check for download changes
        id: check-changes
        run: |
          if [ "$(git status --porcelain assets/data/download-stats.json assets/data/block.properties assets/data/addedMods.md | wc -l)" -gt "0" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi
          echo "Download changes: $(git status --porcelain assets/data/download-stats.json assets/data/block.properties assets/data/addedMods.md | wc -l)"

      # Upload download data artifacts if changed
      - name: Upload download data artifacts
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: download-data
          path: |
            assets/data/download-stats.json
            assets/data/block.properties
            assets/data/addedMods.md
          retention-days: 1

  update-translations:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      has_changes: ${{ steps.check-changes.outputs.has_changes }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Create translations directory if needed
        run: mkdir -p how-to-install/translations
        
      - name: Fetch latest translation files
        run: |
          # Create temp dir for language files
          mkdir -p temp_lang
          
          # Clone only the needed directory from the langFiles repository
          git clone --depth 1 --filter=blob:none --sparse https://github.com/EuphoriaPatches/langFiles.git temp_lang
          cd temp_lang
          git sparse-checkout set website
          cd ..
          
          # Copy all json files to the translations directory
          cp -f temp_lang/website/*.json how-to-install/translations/
          
          # Clean up
          rm -rf temp_lang
      
      # Check if there were changes to any translation files
      - name: Check for translation changes
        id: check-changes
        run: |
          if [ "$(git status --porcelain how-to-install/translations/ | wc -l)" -gt "0" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "Translation changes detected: $(git status --porcelain how-to-install/translations/ | wc -l) files"
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "No translation changes detected"
          fi
      
      # Upload translation files as an artifact if changed
      - name: Upload translation data artifacts
        if: steps.check-changes.outputs.has_changes == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: translation-data
          path: how-to-install/translations/
          retention-days: 1

  commit-and-push:
    runs-on: ubuntu-latest
    needs: [update-contributors, update-downloads, update-translations]
    if: always() && (needs.update-contributors.result == 'success' || needs.update-downloads.result == 'success' || needs.update-translations.result == 'success')
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      # Download contributor data if it was changed
      - name: Download contributor data
        if: needs.update-contributors.outputs.has_changes == 'true'
        uses: actions/download-artifact@v3
        with:
          name: contributors-data
          path: assets/data/
      
      # Download download data if it was changed
      - name: Download download data
        if: needs.update-downloads.outputs.has_changes == 'true'
        uses: actions/download-artifact@v3
        with:
          name: download-data
          path: assets/data/
      
      # Download translation data if it was changed
      - name: Download translation data
        if: needs.update-translations.outputs.has_changes == 'true'
        uses: actions/download-artifact@v3
        with:
          name: translation-data
          path: how-to-install/translations/
      
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      
      - name: Stage contributors file if changed
        if: needs.update-contributors.outputs.has_changes == 'true'
        run: |
          echo "Staging contributor changes"
          git add assets/data/contributors.json
      
      - name: Stage download files if changed
        if: needs.update-downloads.outputs.has_changes == 'true'
        run: |
          echo "Staging download changes"
          git add assets/data/download-stats.json assets/data/block.properties assets/data/addedMods.md
      
      - name: Stage translation files if changed
        if: needs.update-translations.outputs.has_changes == 'true'
        run: |
          echo "Staging translation changes"
          git add how-to-install/translations/*.json
      
      - name: Commit and push all changes
        run: |
          # Only commit if there are staged changes
          git diff --quiet --staged || {
            echo "Committing changes to the repository"
            git commit -m "Update site data [skip ci]"
            
            # Try pushing with retries
            MAX_RETRIES=5
            RETRY_COUNT=0
            
            until git push || [ $RETRY_COUNT -ge $MAX_RETRIES ]; do
              RETRY_COUNT=$((RETRY_COUNT + 1))
              echo "Push failed, retrying (Attempt $RETRY_COUNT/$MAX_RETRIES)..."
              git pull --rebase
            done
            
            echo "Successfully pushed changes"
          }