name: Update Downloads

on:
  schedule:
    - cron: "0 0 * * *" # Every UTC midnight 
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/update-downloads.yml'

jobs:
  update-downloads:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch node-abort-controller

      - name: Run download update script
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        run: node --trace-exit backend/updateDownloads.mjs
        
      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
      - name: Commit and push if there are changes
        run: |
          git add assets/data/download-stats.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update download statistics [skip ci]"
          git push